name: ML Platform CI/CD

on:
  push:
    branches:
      - main

env:
  REGISTRY: myportfolioacrraife.azurecr.io
  IMAGE_OWNER: myportfolioacrraife

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Check frontend changes
        id: check
        run: |
          echo "Before commit: ${{ github.event.before }}"
          echo "After commit: ${{ github.sha }}"
          
          if [[ "${{ github.event.before }}" == "0000000000000000000000000000000000000000" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "Initial commit or unknown, forcing build"
          else
            changes=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^frontend/' || true)
            echo "Changed files in frontend: $changes"
            if [[ -z "$changes" ]]; then
              echo "changed=false" >> $GITHUB_OUTPUT
            else
              echo "changed=true" >> $GITHUB_OUTPUT
            fi
          fi

      - name: Login to ACR
        if: steps.check.outputs.changed == 'true'
        run: echo "${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}" | docker login ${{ env.REGISTRY }} -u ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }} --password-stdin

      - name: Build and push frontend image
        if: steps.check.outputs.changed == 'true'
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/frontend:latest .
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/frontend:latest

  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout code with depth 2
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Check backend changes
        id: check
        run: |
          if [[ "${{ github.event.before }}" == "0000000000000000000000000000000000000000" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            changes=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^backend/' || true)
            if [[ -z "$changes" ]]; then
              echo "changed=false" >> $GITHUB_OUTPUT
            else
              echo "changed=true" >> $GITHUB_OUTPUT
            fi
          fi

      - name: Login to ACR
        if: steps.check.outputs.changed == 'true'
        run: echo "${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}" | docker login ${{ env.REGISTRY }} -u ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }} --password-stdin

      - name: Build and push backend image
        if: steps.check.outputs.changed == 'true'
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/backend:latest .
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/backend:latest

  build-deid:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ml_models/model_deid
    steps:
      - name: Checkout code with depth 2
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Check deid changes
        id: check
        run: |
          if [[ "${{ github.event.before }}" == "0000000000000000000000000000000000000000" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            changes=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^ml_models/model_deid/' || true)
            if [[ -z "$changes" ]]; then
              echo "changed=false" >> $GITHUB_OUTPUT
            else
              echo "changed=true" >> $GITHUB_OUTPUT
            fi
          fi

      - name: Login to ACR
        if: steps.check.outputs.changed == 'true'
        run: echo "${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}" | docker login ${{ env.REGISTRY }} -u ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }} --password-stdin

      - name: Build and push deid image
        if: steps.check.outputs.changed == 'true'
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/model-deid:latest .
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/model-deid:latest

  build-ner:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ml_models/model_ner
    steps:
      - name: Checkout code with depth 2
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Check ner changes
        id: check
        run: |
          if [[ "${{ github.event.before }}" == "0000000000000000000000000000000000000000" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            changes=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^ml_models/model_ner/' || true)
            if [[ -z "$changes" ]]; then
              echo "changed=false" >> $GITHUB_OUTPUT
            else
              echo "changed=true" >> $GITHUB_OUTPUT
            fi
          fi

      - name: Login to ACR
        if: steps.check.outputs.changed == 'true'
        run: echo "${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}" | docker login ${{ env.REGISTRY }} -u ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }} --password-stdin

      - name: Build and push ner image
        if: steps.check.outputs.changed == 'true'
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/model-ner:latest .
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/model-ner:latest

  build-assertion:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ml_models/model_assertion
    steps:
      - name: Checkout code with depth 2
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Check assertion changes
        id: check
        run: |
          if [[ "${{ github.event.before }}" == "0000000000000000000000000000000000000000" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            changes=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^ml_models/model_assertion/' || true)
            if [[ -z "$changes" ]]; then
              echo "changed=false" >> $GITHUB_OUTPUT
            else
              echo "changed=true" >> $GITHUB_OUTPUT
            fi
          fi

      - name: Login to ACR
        if: steps.check.outputs.changed == 'true'
        run: echo "${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}" | docker login ${{ env.REGISTRY }} -u ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }} --password-stdin

      - name: Build and push assertion image
        if: steps.check.outputs.changed == 'true'
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/model-assertion:latest .
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/model-assertion:latest

  build-relation:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ml_models/model_relation
    steps:
      - name: Checkout code with depth 2
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Check relation changes
        id: check
        run: |
          if [[ "${{ github.event.before }}" == "0000000000000000000000000000000000000000" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            changes=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^ml_models/model_relation/' || true)
            if [[ -z "$changes" ]]; then
              echo "changed=false" >> $GITHUB_OUTPUT
            else
              echo "changed=true" >> $GITHUB_OUTPUT
            fi
          fi

      - name: Login to ACR
        if: steps.check.outputs.changed == 'true'
        run: echo "${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}" | docker login ${{ env.REGISTRY }} -u ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }} --password-stdin

      - name: Build and push relation image
        if: steps.check.outputs.changed == 'true'
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/model-relation:latest .
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/model-relation:latest

  build-classification:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ml_models/model_cls
    steps:
      - name: Checkout code with depth 2
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Check classification changes
        id: check
        run: |
          if [[ "${{ github.event.before }}" == "0000000000000000000000000000000000000000" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            changes=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^ml_models/model_cls/' || true)
            if [[ -z "$changes" ]]; then
              echo "changed=false" >> $GITHUB_OUTPUT
            else
              echo "changed=true" >> $GITHUB_OUTPUT
            fi
          fi

      - name: Login to ACR
        if: steps.check.outputs.changed == 'true'
        run: echo "${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}" | docker login ${{ env.REGISTRY }} -u ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }} --password-stdin

      - name: Build and push classification image
        if: steps.check.outputs.changed == 'true'
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/model-classification:latest .
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/model-classification:latest
